### ISSUE TITLE
Bees lose their names when working

### ISSUE THREAD

**Issue by ShibeTemple** [HexagonNico/BuzzyDrones#2]
Hi :)

If you name a bee drone with a nametag, it will lose its name after going into and leaving a station. I believe this might be because you are spawning a new entity and not inheriting the tag attributes including the name? 

It would be nice to be able to name the bees!

**Comment by HexagonNico** [comment]
Version 2.0.1 has been uploaded to CurseForge. Drones can now be renamed with an anvil or with a name tag and they will keep their name.
